# Generated by Django 5.2.4 on 2025-08-01 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('attendance', models.CharField(choices=[('Solo', 'Solo'), ('Family', 'Family'), ('Sister', 'Sister'), ('Friends', 'Friends')], default='Solo', max_length=10)),
                ('intro_text', models.CharField(max_length=300)),
                ('main_image', models.ImageField(blank=True, upload_to='images/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
